version: "3.7"
name: monitoring

volumes:
    prometheus: {}

services:
  loki:
    image: registry.docker.ir/grafana/loki:2.6.1
    ports:
      - "3100"
    networks:
      - netdevops-net
    volumes:
      # directory must be created first, with uid:gid 10001:10001
      - ./volumes/loki:/loki

  promtail:
    image: registry.docker.ir/grafana/promtail:2.6.1
    volumes:
      # custom config will read logs from the containers of
      # this project
      - ./loki/promtail-config.yaml:/etc/promtail/config.yml
      # to read container labels and logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - netdevops-net


  # will be available at http://127.0.0.1:3000
  # default credentials: admin/admin
  grafana:
    image: registry.docker.ir/grafana/grafana:9.2.2
    ports:
      - "3000:3000"
    volumes:
      # directory must be created first, with uid:gid 472:472
      - ./volumes/grafana:/var/lib/grafana
      # automatically configure the loki datasource
      - ./loki/grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - netdevops-net

  cadvisor:
    image: gcr.stg.dc.afranet.co/cadvisor/cadvisor
    networks:
      - netdevops-net
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  prometheus:
    image: prom/prometheus:v2.5.0
    ports:
      - "9090:9090"
    networks:
      - netdevops-net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=${PROMETHEUS_RETENTION:-24h}'
    volumes:
      - prometheus:/prometheus
      - ./prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
networks:
  netdevops-net:
    external: true
